# Built with Jekyll 3.6.0

# Setup
title:               Onitsha Market Literature
tagline:             'Stories, plays, and pamphlets from the market town of Onitsha, Nigeria'
description:         'Colonial-era print culture: Onitsha Market Literature consists of stories, plays, advice and moral discourses published primarily in the 1960s by local presses in the lively market town of Onitsha, an important commercial site in the Igbo-speaking region of southeastern Nigeria. In the fresh and vigorous genre of Onitsha Market Literature, the commoner wrote pulp fiction and didactic handbooks for those who perused the bookstalls of Onitsha Market, one of Africa’s largest trading centers.'
url:                 'http://idrhku.github.io'
baseurl:             '/onitsha-market'

# About/contact
author:
  name:              James Yeku
  url:               https://twitter.com/jamesyeku
  email:             jyeku@ku.edu

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
